{% set name = "pd2_ca2main" %}
{% set version = "0.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/jmacdona/pd2_public.git
    git_rev: master
    patches:
    - register.patch
    - scons.patch
  - path: env_vars

build:
  features:
  - arch_{{ architecture }}
  string: {{ architecture }}_{{ environ.get("BUILD_NUMBER", 0) }}
  script_env:
  - SCONSFLAGS
  script: |
    export CXXFLAGS=$(
        echo "$CXXFLAGS" | sed \
        -e 's/-O[^ ]\+/-O3/' \
        -e 's/-march=[^ ]\+/-march={{ architecture }}/' \
        -e 's/-mtune=[^ ]\+//')
    export CXXFLAGS="$CXXFLAGS -Wall"
    export CPPFLAGS=$( echo "$CPPFLAGS" | sed 's/-O[^ ]\+//' )

    scons .
    install -m755 -d "$PREFIX/bin"
    install -m755 bin/* "$PREFIX/bin"

    install -m755 -d "$PREFIX/share/pd2_ca2main"
    cp -r database "$PREFIX/share/pd2_ca2main"

    install -m755 -d "$PREFIX/etc/conda/activate.d"
    install -m755 -d "$PREFIX/etc/conda/deactivate.d"
    install -m755 "$SRC_DIR/activate.d/pd2_ca2main.sh" "$PREFIX/etc/conda/activate.d"
    install -m755 "$SRC_DIR/deactivate.d/pd2_ca2main.sh" "$PREFIX/etc/conda/deactivate.d"

requirements:
  build:
  - {{ compiler('cxx') }}
  - scons
  - gsl
  - libboost
  - perl
  host:
  - libboost
  - gsl
  - eigen >=3.3.3
  run:
  - gsl
  - libboost

about:
  home: https://github.com/jmacdona/pd2_public
  license: proprietary
  license_file: COPYRIGHT.TXT
